# -*- coding: utf-8 -*-
"""Movie Recommendation Chat Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QLr6GlgLvI95Rq0LMbOBSp5mo7PuZLa-
"""

import os
import requests
import json
import tmdbsimple as tmdb
import re # Import regex module for year extraction

# --- API Key Configuration for Google Colab ---
# IMPORTANT: Choose ONE of the following methods to set your API keys.

# METHOD 1: Directly assign keys to Python variables (least secure, but quick for testing)
# Replace "YOUR_ACTUAL_TMDB_API_KEY" and "YOUR_ACTUAL_SARVAM_API_KEY" with your actual keys.
# TMDB_API_KEY = "YOUR_ACTUAL_TMDB_API_KEY"
# SARVAM_KEY = "YOUR_ACTUAL_SARVAM_API_KEY"

# METHOD 2: Set as environment variables within the Colab notebook using os.environ
# This makes them accessible via os.getenv() later in the script.
# Replace "YOUR_ACTUAL_TMDB_API_KEY" and "YOUR_ACTUAL_SARVAM_API_KEY" with your keys.
os.environ["TMDB_API_KEY"] = "YOUR_ACTUAL_TMDB_API_KEY" # <<< REMEMBER TO REPLACE THIS WITH YOUR REAL KEY
os.environ["SARVAM_API_KEY"] = "YOUR_ACTUAL_SARVAM_API_KEY" # <<< REMEMBER TO REPLACE THIS WITH YOUR REAL KEY


# METHOD 3 (RECOMMENDED FOR SENSITIVE DATA): Use Colab Secrets
# 1. In Colab, click the "key" icon (🔑) on the left sidebar.
# 2. Click "Add new secret".
# 3. For "Name", enter "TMDB_API_KEY" and for "Value", paste your TMDb API key.
# 4. Click "Add new secret" again.
# 5. For "Name", enter "SARVAM_API_KEY" and for "Value", paste your Sarvam AI API key.
# 6. Make sure "Notebook access" is toggled ON for both secrets.
# Then, uncomment the following lines to retrieve them:
# from google.colab import userdata
# TMDB_API_KEY = userdata.get('TMDB_API_KEY')
# SARVAM_KEY = userdata.get('SARVAM_API_KEY')


# Retrieve keys using os.getenv() (works for Method 2 and if set via Colab Secrets)
TMDB_API_KEY = os.getenv("TMDB_API_KEY")
SARVAM_KEY = os.getenv("SARVAM_API_KEY")

# Validate that keys are available
if not TMDB_API_KEY or TMDB_API_KEY == "YOUR_ACTUAL_TMDB_API_KEY":
    print("Error: TMDB_API_KEY is not set or is still the placeholder.")
    print("Please set it using one of the methods described in the 'API Key Configuration' section.")
    exit(1) # Exit the script if API key is missing

if not SARVAM_KEY or SARVAM_KEY == "YOUR_ACTUAL_SARVAM_API_KEY":
    print("Error: SARVAM_API_KEY is not set or is still the placeholder.")
    print("Please set it using one of the methods described in the 'API Key Configuration' section.")
    exit(1) # Exit the script if API key is missing

# Set TMDb API key
tmdb.API_KEY = TMDB_API_KEY # Assigns the retrieved TMDb API key to the tmdbsimple library.

# Sarvam AI Chat Completion service configuration
SARVAM_CHAT_URL = "https://api.sarvam.ai/v1/chat/completions" # Defines the API endpoint URL for Sarvam AI's chat completion service.
HEADERS = {
    "API-Subscription-Key": SARVAM_KEY, # Sets the API subscription key for authentication with Sarvam AI.
    "Content-Type": "application/json" # Specifies that the request body will be in JSON format.
}

# --- TMDb Helper Functions ---

def get_movie_genre_ids():
    """
    Fetches movie genre IDs and their names from TMDb.
    This function interacts with TMDb to get a list of all available movie genres
    and maps their names (lowercase) to their corresponding IDs.
    """
    try:
        g = tmdb.Genres() # Creates an instance of the TMDb Genres API.
        genres = {x['name'].lower(): x['id'] for x in g.movie_list()['genres']} # Fetches movie genres and creates a dictionary.
        print(f"Successfully fetched {len(genres)} movie genres from TMDb.") # Prints a success message.
        return genres # Returns the dictionary of movie genres.
    except tmdb.exceptions.TMDbException as e: # Catches exceptions specific to TMDb API calls.
        print(f"Error fetching movie genres from TMDb: {e}") # Prints the error message.
        print("Please check your TMDb API key and network connection. Exiting.") # Provides troubleshooting advice.
        exit(1) # Exits the script due to a critical error.
    except requests.exceptions.RequestException as e: # Catches general network-related exceptions.
        print(f"Network error fetching movie genres from TMDb: {e}") # Prints the network error message.
        print("Please check your internet connection. Exiting.") # Provides troubleshooting advice.
        exit(1) # Exits the script due to a critical error.

def get_tv_genre_ids():
    """
    Fetches TV show genre IDs and their names from TMDb.
    Similar to get_movie_genre_ids, but for TV show genres.
    """
    try:
        g = tmdb.Genres() # Creates an instance of the TMDb Genres API.
        genres = {x['name'].lower(): x['id'] for x in g.tv_list()['genres']} # Fetches TV show genres and creates a dictionary.
        print(f"Successfully fetched {len(genres)} TV genres from TMDb.") # Prints a success message.
        return genres # Returns the dictionary of TV show genres.
    except tmdb.exceptions.TMDbException as e: # Catches exceptions specific to TMDb API calls.
        print(f"Error fetching TV genres from TMDb: {e}") # Prints the error message.
        print("Please check your TMDb API key and network connection. Exiting.") # Provides troubleshooting advice.
        exit(1) # Exits the script due to a critical error.
    except requests.exceptions.RequestException as e: # Catches general network-related exceptions.
        print(f"Network error fetching TV genres from TMDb: {e}") # Prints the network error message.
        print("Please check your internet connection. Exiting.") # Provides troubleshooting advice.
        exit(1) # Exits the script due to a critical error.

# Global variables to store genre maps, initialized once
MOVIE_GENRE_MAP = get_movie_genre_ids() # Calls the function to get movie genres and stores them globally.
TV_GENRE_MAP = get_tv_genre_ids() # Calls the function to get TV show genres and stores them globally.

def parse_genres(user_text: str, media_type: str) -> list[int]:
    """
    Parses user input text to identify relevant TMDb genre IDs based on media type.
    It checks for specific keywords like 'anime' and then iterates through the
    appropriate genre map (movie or TV) to find matches.
    """
    user_text_lower = user_text.lower() # Converts user input to lowercase for case-insensitive matching.
    hits = [] # Initializes an empty list to store found genre IDs.

    genre_map_to_use = MOVIE_GENRE_MAP if media_type == 'movie' else TV_GENRE_MAP # Selects the correct genre map based on media type.

    # Check for 'anime' or 'animation' specifically
    if 'anime' in user_text_lower or 'animation' in user_text_lower: # Checks if 'anime' or 'animation' keywords are present.
        if 'animation' in genre_map_to_use: # Verifies if 'animation' genre exists in the selected map.
            hits.append(genre_map_to_use['animation']) # Adds the animation genre ID if found.
        else:
            print(f"Warning: 'Animation' genre not found in TMDb {media_type} genre map. Using default.") # Warns if animation genre is missing.

    # Add other detected genres, ensuring no duplicates
    for w in genre_map_to_use: # Iterates through all genre names in the selected map.
        if w in user_text_lower and genre_map_to_use[w] not in hits: # Checks if genre name is in user text and not already added.
            hits.append(genre_map_to_use[w]) # Adds the genre ID to the hits list.

    # Sensible default if no genres detected
    if not hits: # If no genres were detected from the user's input.
        if media_type == 'movie':
            return [genre_map_to_use.get('drama', list(genre_map_to_use.values())[0])] # Defaults to 'drama' for movies or the first available genre.
        else: # media_type == 'tv'
            return [genre_map_to_use.get('documentary', list(genre_map_to_use.values())[0])] # Defaults to 'documentary' for TV shows or the first available genre.
    return hits # Returns the list of identified genre IDs.

def extract_year(user_text: str) -> int | None:
    """
    Extracts a four-digit year from the user's input text using regular expressions.
    """
    match = re.search(r'\b(19\d{2}|20\d{2})\b', user_text) # Uses regex to find a 4-digit number that looks like a year.
    if match: # If a match is found.
        try:
            year = int(match.group(0)) # Converts the matched string to an integer.
            if 1900 <= year <= 2100: # Basic validation to ensure the year is within a reasonable range.
                return year # Returns the extracted year.
        except ValueError: # Catches error if conversion to int fails.
            pass # Ignores the error and proceeds.
    return None # Returns None if no valid year is found.

def extract_language(user_text: str) -> str | None:
    """
    Extracts a language/industry keyword (like 'Bollywood', 'Japanese') from user input
    and maps it to TMDb's ISO 639-1 language code (e.g., 'hi', 'ja').
    """
    user_text_lower = user_text.lower() # Converts user input to lowercase.

    language_map = { # Defines a dictionary mapping common language/industry keywords to ISO codes.
        'hindi': 'hi', 'bollywood': 'hi', 'indian': 'hi',
        'japanese': 'ja', 'korean': 'ko', 'mandarin': 'zh', 'chinese': 'zh',
        'english': 'en', 'hollywood': 'en', 'american': 'en',
        'spanish': 'es', 'french': 'fr', 'german': 'de', 'italian': 'it',
        'arabic': 'ar', 'russian': 'ru', 'portuguese': 'pt'
    }

    for keyword, lang_code in language_map.items(): # Iterates through the language map.
        if keyword in user_text_lower: # Checks if the keyword is present in the user's input.
            print(f"Detected language/industry keyword: '{keyword}', mapping to '{lang_code}'") # Prints the detected keyword and its mapping.
            return lang_code # Returns the corresponding ISO language code.
    return None # Returns None if no language/industry keyword is found.

def discover_movies(genre_ids: list[int], year: int | None = None, language: str | None = None, pages: int = 2) -> list[dict]:
    """
    Discovers movies from TMDb based on genre IDs, optional year, and optional language.
    Results are sorted by popularity in descending order.
    """
    movies = [] # Initializes an empty list to store discovered movies.
    discover = tmdb.Discover() # Creates an instance of the TMDb Discover API.
    print(f"Discovering movies for genres: {genre_ids} (Year: {year if year else 'Any'}, Language: {language if language else 'Any'})...") # Prints discovery parameters.

    discover_params = { # Dictionary to hold parameters for the TMDb API call.
        'with_genres': ','.join(map(str, genre_ids)), # Joins genre IDs into a comma-separated string.
        'page': 1, # Starts discovery from the first page.
        'sort_by': 'popularity.desc' # Sorts results by popularity in descending order (most popular first).
    }
    if year: # If a year is provided.
        discover_params['primary_release_year'] = year # Adds the primary release year parameter.
    if language: # If a language is provided.
        discover_params['with_original_language'] = language # Adds the original language parameter.

    for p in range(1, pages + 1): # Loops through the specified number of pages.
        discover_params['page'] = p # Sets the current page number for the API call.
        try:
            resp = discover.movie(**discover_params) # Makes the TMDb movie discovery API call with all parameters.
            movies.extend(resp['results']) # Adds the movies from the current page to the list.
            print(f"  Fetched {len(resp['results'])} movies from TMDb page {p}.") # Prints the number of movies fetched from the page.
        except tmdb.exceptions.TMDbException as e: # Catches TMDb specific API errors.
            print(f"  Warning: Error discovering movies from TMDb (page {p}): {e}") # Prints a warning but continues.
            continue # Continues to the next page.
        except requests.exceptions.RequestException as e: # Catches general network errors.
            print(f"  Warning: Network error discovering movies from TMDb (page {p}): {e}") # Prints a warning but continues.
            continue # Continues to the next page.
    print(f"Total discovered movies: {len(movies[:100])}") # Prints the total number of movies discovered (capped at 100).
    return movies[:100] # Returns the first 100 discovered movies.

def discover_tv_shows(genre_ids: list[int], year: int | None = None, language: str | None = None, pages: int = 2) -> list[dict]:
    """
    Discovers TV shows from TMDb based on genre IDs, optional year, and optional language.
    Results are sorted by popularity.
    Similar to discover_movies, but for TV shows.
    """
    tv_shows = [] # Initializes an empty list to store discovered TV shows.
    discover = tmdb.Discover() # Creates an instance of the TMDb Discover API.
    print(f"Discovering TV shows for genres: {genre_ids} (Year: {year if year else 'Any'}, Language: {language if language else 'Any'})...") # Prints discovery parameters.

    discover_params = { # Dictionary to hold parameters for the TMDb API call.
        'with_genres': ','.join(map(str, genre_ids)), # Joins genre IDs into a comma-separated string.
        'page': 1, # Starts discovery from the first page.
        'sort_by': 'popularity.desc' # Sorts results by popularity in descending order (most popular first).
    }
    if year: # If a year is provided.
        # For TV shows, 'first_air_date_year' is used for release year
        discover_params['first_air_date_year'] = year # Adds the first air date year parameter.
    if language: # If a language is provided.
        discover_params['with_original_language'] = language # Adds the original language parameter.

    for p in range(1, pages + 1): # Loops through the specified number of pages.
        discover_params['page'] = p # Sets the current page number for the API call.
        try:
            resp = discover.tv(**discover_params) # Makes the TMDb TV show discovery API call with all parameters.
            tv_shows.extend(resp['results']) # Adds the TV shows from the current page to the list.
            print(f"  Fetched {len(resp['results'])} TV shows from TMDb page {p}.") # Prints the number of TV shows fetched from the page.
        except tmdb.exceptions.TMDbException as e: # Catches TMDb specific API errors.
            print(f"  Warning: Error discovering TV shows from TMDb (page {p}): {e}") # Prints a warning but continues.
            continue # Continues to the next page.
        except requests.exceptions.RequestException as e: # Catches general network errors.
            print(f"  Warning: Network error discovering TV shows from TMDb (page {p}): {e}") # Prints a warning but continues.
            continue # Continues to the next page.
    print(f"Total discovered TV shows: {len(tv_shows[:100])}") # Prints the total number of TV shows discovered (capped at 100).
    return tv_shows[:100] # Returns the first 100 discovered TV shows.


# --- Core Recommendation Function using Sarvam AI Chat API ---

def get_chat_recommendation(user_preference: str, media_list_from_tmdb: list[dict], media_type: str) -> str:
    """
    Generates a recommendation using the Sarvam AI chat completion API,
    based on user preference and a provided list of movies/TV shows from TMDb.
    The AI is prompted to consider popularity and rating from the provided data.
    """
    print(f"Sending request to Sarvam AI chat model with TMDb {media_type} data...") # Informs about the API call.

    # Prepare media data for the prompt to avoid exceeding token limits
    # We'll send a subset of the media to the AI for selection
    # The list is already sorted by popularity from TMDb discovery functions
    media_for_ai_prompt = media_list_from_tmdb[:20] # Limits the list of media sent to the AI to the top 20, to manage token limits.

    media_list_str = "" # Initializes an empty string to build the list of media for the AI prompt.
    if not media_for_ai_prompt: # Checks if any media were found.
        media_list_str = f"No {media_type}s were found from TMDb to recommend from." # Message if no media are available.
    else:
        for i, item in enumerate(media_for_ai_prompt): # Iterates through the selected media items.
            # Use 'title' for movies, 'name' for TV shows
            title_or_name = item.get('title', item.get('name', 'N/A')) # Gets the title (for movies) or name (for TV shows).
            overview = item.get('overview', 'No overview available') # Gets the overview/synopsis.
            # Include popularity and vote average in the prompt for AI to consider
            popularity = item.get('popularity', 'N/A') # Gets the popularity score.
            vote_average = item.get('vote_average', 'N/A') # Gets the average rating.
            media_list_str += ( # Appends formatted media details to the string.
                f"Title/Name: {title_or_name}\n"
                f"Overview: {overview}\n"
                f"Popularity: {popularity}\n"
                f"Rating (Vote Average): {vote_average}\n"
                f"---\n"
            )

    # Add a warning if the media list string is very long, as it can hit token limits
    if len(media_list_str) > 5000: # Checks if the generated string might exceed typical model context windows.
        print(f"Warning: {media_type.capitalize()} list string length is {len(media_list_str)}. This might exceed model's context window.") # Prints a warning.

    # Define the messages for the chat model
    messages = [ # Defines the conversation history/prompt for the AI.
        {
            "role": "system", # The system message sets the AI's persona and instructions.
            "content": ( # Content of the system message.
                f"You are a helpful and friendly {media_type} recommendation assistant. "
                f"You will be given a user's {media_type} preference and a list of {media_type}s with their overviews, popularity, and ratings. "
                f"The provided list is already sorted by popularity, with the most popular items at the top. "
                f"Your task is to recommend 3-5 {media_type}s *from the provided list* that best match the user's preference, "
                f"considering their popularity and rating as additional factors. "
                f"For each recommendation, provide the {media_type} title/name and a brief, engaging description based on its overview. "
                f"If no {media_type}s from the provided list are a good match, politely state that and suggest trying a different preference or genre."
                f"Do not invent {media_type}s or details not present in the provided list."
            )
        },
        {
            "role": "user", # The user message contains the specific request and data.
            "content": ( # Content of the user message.
                f"My {media_type} preference is: {user_preference}\n\n"
                f"Here is a list of {media_type}s to choose from (sorted by popularity):\n\n{media_list_str}\n"
                f"Please recommend 3-5 {media_type}s from this list that best fit my preference. "
                f"Only recommend {media_type}s from the list provided. "
                f"For each recommendation, state the title/name and a brief description."
            )
        }
    ]

    # Define the payload for the chat completion API
    payload = { # Dictionary defining the request body for the Sarvam AI API.
        "model": "sarvam-m", # Specifies the AI model to use for chat completion.
        "messages": messages, # The conversation history/prompt for the AI.
        "max_tokens": 500, # Maximum number of tokens the AI should generate in its response.
        "temperature": 0.7 # Controls the randomness/creativity of the AI's response (0.0 is deterministic, 1.0 is very creative).
    }

    print("\n--- Debug Info: Request Payload ---") # Debugging print statement.
    print(json.dumps(payload, indent=2)) # Prints the JSON payload in a human-readable format.
    print("-----------------------------------\n") # Separator for debug info.

    try:
        # Send POST request to Sarvam AI chat completion service
        response = requests.post(SARVAM_CHAT_URL, json=payload, headers=HEADERS, timeout=30) # Sends the HTTP POST request.
        response.raise_for_status()  # Raises an HTTPError for bad responses (4xx or 5xx status codes).

        response_data = response.json() # Parses the JSON response from the API.

        # Extract the AI's response
        if response_data and response_data.get('choices'): # Checks if the response contains choices.
            ai_response = response_data['choices'][0]['message']['content'] # Extracts the AI's generated content.
            print("Successfully received recommendation from Sarvam AI.") # Prints a success message.
            return ai_response # Returns the AI's recommendation.
        else:
            raise ValueError(f"Unexpected response structure from Sarvam AI: {response_data}") # Raises error for unexpected response format.

    except requests.exceptions.RequestException as e: # Catches any request-related exceptions (e.g., network issues, HTTP errors).
        print(f"\n--- Debug Info: Raw API Response (if available) ---") # Debugging print statement.
        print(f"HTTP Status Code: {e.response.status_code if hasattr(e, 'response') and e.response is not None else 'N/A'}") # Prints HTTP status code.
        print(f"HTTP Reason: {e.response.reason if hasattr(e, 'response') and e.response is not None else 'N/A'}") # Prints HTTP reason phrase.
        if hasattr(e, 'response') and e.response is not None: # Checks if a response object is available.
            print(e.response.text) # Prints the raw response body from the API (often contains detailed error messages).
        else:
            print("No raw response text available.") # Message if no raw response is available.
        print("---------------------------------------------------\n") # Separator for debug info.
        raise RuntimeError( # Raises a custom runtime error for better error handling.
            f"Error calling Sarvam AI chat completion service: {e}. "
            "This is likely a 4xx or 5xx HTTP error. "
            "Please check your SARVAM_API_KEY, verify the SARVAM_CHAT_URL, "
            "and ensure the 'model' name is correct in the payload."
        ) from e # Chains the original exception for better traceback.
    except KeyError as e: # Catches errors if expected keys are missing in the JSON response.
        raise RuntimeError( # Raises a custom runtime error.
            f"Unexpected response structure from Sarvam AI: {response_data}. "
            f"Missing key: {e}. 'choices', 'message', or 'content' might be missing."
        ) from e # Chains the original exception.
    except ValueError as e: # Catches other value-related errors.
        raise RuntimeError(f"Data error from Sarvam AI: {e}") from e # Raises a custom runtime error.

# --- User Input Collection ---

def collect_user_preference_basic():
    """Basic method to collect user movie/TV show preference"""
    print("\n🎬 Movie/TV Show Recommendation System (TMDb + AI Chat Powered)")
    print("---------------------------------")

    media_type_choice = ""
    while media_type_choice not in ['movie', 'tv']:
        media_type_choice = input("Do you want to search for a [movie] or a [tv] show? ").lower().strip()
        if media_type_choice not in ['movie', 'tv']:
            print("Invalid choice. Please type 'movie' or 'tv'.")

    print(f"Tell me what kind of {media_type_choice} you're in the mood for:")
    print("(Describe your preferences in detail - genre, mood, style, year, language/industry, etc.)") # Updated prompt
    print()

    user_input = input(f"Your {media_type_choice} preference: ")
    return user_input.strip(), media_type_choice

# --- Main execution flow for the script ---
if __name__ == "__main__":
    user_preference, media_type = collect_user_preference_basic()

    if not user_preference:
        print("No preference entered. Exiting.")
        exit(0)

    print(f"\nYou said: {user_preference}")
    print(f"\nFetching {media_type}s from TMDb and generating recommendation using Sarvam AI Chat...")

    try:
        # Extract year and language first
        release_year = extract_year(user_preference)
        if release_year:
            print(f"Detected year: {release_year}")

        original_language = extract_language(user_preference)
        if original_language:
            print(f"Detected language/industry: {original_language}")

        # Parse genres based on selected media type
        genres = parse_genres(user_preference, media_type)
        print(f"Inferred genre IDs: {genres}")

        # Discover media based on type, genres, year, and language from TMDb
        if media_type == 'movie':
            media_list_from_tmdb = discover_movies(genres, year=release_year, language=original_language)
        else: # media_type == 'tv'
            media_list_from_tmdb = discover_tv_shows(genres, year=release_year, language=original_language)

        if not media_list_from_tmdb:
            print(f"No {media_type}s found from TMDb for the specified criteria. Try a different description or broaden your search.")
            exit(0)

        # Get recommendation from the Sarvam AI chat model, providing TMDb media
        recommendation_text = get_chat_recommendation(user_preference, media_list_from_tmdb, media_type)

        print("\n--- Your Movie/TV Show Recommendation ---")
        print(recommendation_text)
        print("\n---------------------------------")

    except Exception as e:
        print(f"\nAn unexpected error occurred during recommendation: {e}")
        print("Please review the error message and ensure your API keys are correct and network is stable.")